services:
  db:
    image: postgres:14.8-alpine3.18
    container_name: short-url-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=shorturl
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    networks:
      - short-url

  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: 'short-url-api:latest'
    container_name: short-url-api
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://user:1234@db:5432/shorturl?schema=public
      - BASE_URL=http://localhost:8001
    ports:
      - 8001:8000
    networks:
      - short-url
    depends_on:
      - db

networks:
  short-url:
